# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: VE3MAL Station Notebook
email: ve3mal@rac.ca
description: >- # this means to ignore newlines until "baseurl:"
  Ham Radio project notebook and log for VE3MAL (Jay), an Amateur Radio operator
  in southern Ontario. Member of Kitchener Amateur Radio
  Club (KWARC) and Radio Amateurs of Canada (RAC). Find on Mastodon
  @ve3mal@mastodon.radio, and on the \#Amateurradio on the Geekshed IRC
  Network.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ve3mal.locklin.science" # the base hostname & protocol for your site, e.g. http://example.com
  #twitter_username: jekyllrb
github_username: JasonLocklin
author: VE3MAL
timezone: America/Toronto
timezone_short: ET


# Keywords
keywords: ['Ham Radio', 'QRP', 'POTA', 'HF']

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 6
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    layouts: 
      - 'autopage_category.html'
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false
    slugify:
      mode: 'default'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: false       # Whether to replace all uppercase letters with their lowercase counterparts

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
